### ISSUE TITLE
Error when importing into StatioScout

### ISSUE THREAD

**Issue by ni8towl** [krusehansenjens/gen_test_case-#1]
![Capture](https://github.com/krusehansenjens/gen_test_case/assets/76158215/acbad1e8-dfa4-4f48-8046-2119e3fd584f)
Getting error message when json created from GUI_test.py. Used the given example excel and scd file without modification.

**Comment by ni8towl** [comment]
![Capture3](https://github.com/krusehansenjens/gen_test_case/assets/76158215/d1ea1695-3778-4236-8ee2-0fc203293368)
Error message disappears when groupType is put in the order of CONTROL>ASSESS>COMMAND

**Comment by aliabd00** [comment]
Resolved with Generate_Test_Case_Ver6.py

**Comment by ni8towl** [comment]
Resolved with Generate_Test_Case_Ver6.py
